"""Export Pydantic config schemas to JSON Schema files."""

import importlib
import json
from pathlib import Path

from pydantic.json_schema import GenerateJsonSchema

from nuthatch.config import GlobalConfigSchema, ProjectConfigSchema

SCHEMA_DIR = Path(__file__).parents[2]  # nuthatch/ project root


class _NuthatchJsonSchema(GenerateJsonSchema):
    """Use model ConfigDict title as the $defs key when set."""

    def normalize_name(self, name: str) -> str:
        cls = getattr(importlib.import_module("nuthatch.config"), name, None)
        if cls is not None and hasattr(cls, "model_config"):
            title = cls.model_config.get("title")
            if title:
                return title
        return super().normalize_name(name)


_KEY_ORDER = [
    "$schema",
    "$id",
    "$comment",
    "$ref",
    "title",
    "type",
    "description",
    "additionalProperties",
    "items",
    "properties",
    "$defs",
]


def _build_def_rank():
    """Rank $defs keys by model definition order in nuthatch.config."""
    config_mod = importlib.import_module("nuthatch.config")
    rank = {}
    i = 0
    for obj in config_mod.__dict__.values():
        if isinstance(obj, type) and hasattr(obj, "model_config"):
            title = obj.model_config.get("title") or obj.__name__
            rank[title] = i
            i += 1
    return rank


_DEF_RANK = _build_def_rank()


def _sort_keys(obj, parent_key=None):
    """Recursively sort schema keyword keys; field order follows model definition order."""
    if isinstance(obj, list):
        return [_sort_keys(item) for item in obj]
    if not isinstance(obj, dict):
        return obj
    if parent_key == "$defs":
        return {k: _sort_keys(obj[k], k) for k in sorted(obj, key=lambda k: _DEF_RANK.get(k, len(_DEF_RANK)))}
    if parent_key == "properties":
        return {k: _sort_keys(v, k) for k, v in obj.items()}
    return {
        k: _sort_keys(obj[k], k)
        for k in sorted(obj, key=lambda k: (_KEY_ORDER.index(k) if k in _KEY_ORDER else len(_KEY_ORDER), k))
    }


def _clean(obj):
    """Recursively clean up Pydantic schema output."""
    if isinstance(obj, list):
        return [_clean(item) for item in obj]
    if not isinstance(obj, dict):
        return obj

    # Collapse anyOf [X, {type: null}] -> X (nullable fields)
    if "anyOf" in obj:
        non_null = [s for s in obj["anyOf"] if s != {"type": "null"}]
        if len(non_null) == 1:
            result = _clean(non_null[0])
            if "description" in obj:
                result["description"] = obj["description"]
            return result

    return {k: _clean(v) for k, v in obj.items() if k not in ("title", "default")}


_GENERATED_COMMENT = "This file is auto-generated by nuthatch-export-schema. Do not edit manually."


def _export(model, path, schema_id, title, description):
    schema = _clean(model.model_json_schema(schema_generator=_NuthatchJsonSchema))
    schema = {
        "$schema": "http://json-schema.org/draft-07/schema#",
        "$id": schema_id,
        "$comment": _GENERATED_COMMENT,
        "title": title,
        **schema,
        "description": description,
    }
    Path(path).write_text(json.dumps(_sort_keys(schema), indent=2) + "\n")


def main():
    _export(
        GlobalConfigSchema,
        SCHEMA_DIR / "nuthatch-global.schema.json",
        "https://github.com/rhiza-research/nuthatch/nuthatch-global.schema.json",
        "Nuthatch Global Configuration",
        "Schema for ~/.nuthatch.toml global configuration",
    )
    _export(
        ProjectConfigSchema,
        SCHEMA_DIR / "nuthatch.schema.json",
        "https://github.com/rhiza-research/nuthatch/nuthatch.schema.json",
        "Nuthatch Configuration",
        "Schema for nuthatch.toml configuration files",
    )


if __name__ == "__main__":
    main()
