# GCP infrastructure for nuthatch integration tests

variable "gcs_bucket_name" {
  description = "Name of the GCS test bucket"
  type        = string
  default     = "nuthatch-test-bucket"
}

variable "gcs_location" {
  description = "Bucket location"
  type        = string
  default     = "us-central1"
}

variable "gcp_org_id" {
  description = "GCP organization ID"
  type        = string
}

variable "gcp_billing_account" {
  description = "GCP billing account ID"
  type        = string
}

resource "google_project" "nuthatch" {
  name            = "nuthatch"
  project_id      = "nuthatch-488521"
  org_id          = var.gcp_org_id
  billing_account = var.gcp_billing_account
}

resource "google_project_service" "storage" {
  project = google_project.nuthatch.project_id
  service = "storage.googleapis.com"
}

resource "google_project_service" "iam" {
  project = google_project.nuthatch.project_id
  service = "iam.googleapis.com"
}

provider "google" {
}

resource "google_storage_bucket" "test" {
  project                     = google_project.nuthatch.project_id
  name                        = var.gcs_bucket_name
  location                    = var.gcs_location
  uniform_bucket_level_access = true
  force_destroy               = true
  depends_on                  = [google_project_service.storage]
}

resource "google_service_account" "test" {
  project      = google_project.nuthatch.project_id
  account_id   = "nuthatch-test"
  display_name = "Nuthatch Test Service Account"
  depends_on   = [google_project_service.iam]
}

resource "google_storage_bucket_iam_member" "test" {
  bucket = google_storage_bucket.test.name
  role   = "roles/storage.objectAdmin"
  member = "serviceAccount:${google_service_account.test.email}"
}

resource "google_service_account_key" "test" {
  service_account_id = google_service_account.test.name
}

resource "local_file" "gcs_sa_key" {
  content  = base64decode(google_service_account_key.test.private_key)
  filename = "${path.module}/nuthatch-test-sa-key.json"
}

output "gcs_bucket_name" {
  value = google_storage_bucket.test.name
}

output "gcs_key_file" {
  value = local_file.gcs_sa_key.filename
}

output "gcs_service_account_email" {
  value = google_service_account.test.email
}

output "gcs_project" {
  value = google_project.nuthatch.project_id
}

resource "local_file" "nuthatch_gcp_config" {
  filename = "${path.module}/../nuthatch.gcp.toml"
  content  = <<-EOT
    #:schema https://raw.githubusercontent.com/rhiza-research/nuthatch/main/nuthatch.schema.json
    # Generated by terraform - DO NOT EDIT
    # Test credentials for nuthatch-test bucket

    [root]
    filesystem = "gs://${google_storage_bucket.test.name}/cache"

    [root.filesystem_options]
    project = "${google_project.nuthatch.project_id}"
    token = "test_infrastructure/nuthatch-test-sa-key.json"

    [local]
    filesystem = "~/.nuthatch/local-cache"
  EOT
}
